In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [2]:
# let's get the data import and cleanup out of the way
df = pd.read_csv("dnd_monsters.csv")
used_columns = ['cr', 'ac', 'hp', 'str', 'dex', 'con', 'int', 'wis', 'cha']
df = df[used_columns]
df = df[df['cr'].isna() == False]

def cr_standardiser(x) -> float:
    try:
        return float(x)
    except ValueError:
        if x == '1/8':
            return 0.125
        elif x == '1/4':
            return 0.25
        elif x == '1/2':
            return 0.5
        else:
            raise ValueError(f'unexpected value: {x}')

df['cr'] = df['cr'].apply(cr_standardiser)
df_s = df[df['str'].isna() == False]
nans = dict()
for column in used_columns:
    nans[column] = int(df_s[column].isna().sum())

df

        cr  ac   hp   str   dex   con   int   wis   cha
0     0.25  12   13  10.0  14.0  10.0  11.0  12.0  11.0
1     9.00  12   84   NaN   NaN   NaN   NaN   NaN   NaN
2    10.00  17  135  21.0   9.0  15.0  18.0  15.0  18.0
3     9.00  15  137   NaN   NaN   NaN   NaN   NaN   NaN
4    23.00  21  285   NaN   NaN   NaN   NaN   NaN   NaN
..     ...  ..  ...   ...   ...   ...   ...   ...   ...
757   1.00  11   40  11.0  12.0  11.0  13.0  12.0  14.0
758  22.00  21  307   NaN   NaN   NaN   NaN   NaN   NaN
759  26.00  21  580  27.0  24.0  28.0  26.0  27.0  30.0
760   0.25   8   22  13.0   6.0  16.0   3.0   6.0   5.0
761  23.00  18  304   NaN   NaN   NaN   NaN   NaN   NaN

[761 rows x 9 columns]